# Generated by Django 5.0.6 on 2024-06-17 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='tile',
            new_name='title',
        ),
    ]
